name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./sait
      run: |
        npm install
        npm list --depth=0

    - name: Run linter
      working-directory: ./sait
      run: npm run lint

    - name: Run type check
      working-directory: ./sait
      run: npx tsc --noEmit

    - name: Run tests
      working-directory: ./sait
      run: npm test

    - name: Build application
      working-directory: ./sait
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.node-version }}
        path: sait/dist/
        retention-days: 30

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./sait
      run: |
        npm install
        npm list --depth=0

    - name: Build for production
      working-directory: ./sait
      run: npm run build

    - name: Check build output
      run: |
        echo "📦 Build artifacts:"
        ls -la sait/dist/
        echo ""
        echo "📊 Build size:"
        du -sh sait/dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Используем стабильную версию v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./sait/dist
        # cname: ${{ github.event.repository.name }}.github.io  # Раскомментируйте для кастомного домена

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./sait
      run: |
        npm install
        npm list --depth=0

    - name: Run security audit
      working-directory: ./sait
      run: npm audit --audit-level=moderate



