name: Weekly Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 09:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: sait/package-lock.json

    - name: Install dependencies
      working-directory: ./sait
      run: npm ci

    - name: Check for outdated dependencies
      working-directory: ./sait
      run: npm outdated || true

    - name: Update dependencies
      working-directory: ./sait
      run: |
        npm update
        npm audit fix --audit-level=moderate

    - name: Run tests after update
      working-directory: ./sait
      run: npm test

    - name: Run linter after update
      working-directory: ./sait
      run: npm run lint

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          chore: update dependencies

          - Updated npm dependencies
          - Fixed security vulnerabilities
          - Ran tests and linting
        title: 'chore: weekly dependency updates'
        body: |
          ## Dependency Updates

          This PR contains automated weekly dependency updates.

          ### Changes
          - Updated npm dependencies to latest compatible versions
          - Fixed security vulnerabilities (if any)
          - All tests and linting checks passed

          ### Verification
          - ✅ Tests passed
          - ✅ Linting passed
          - ✅ Build successful

          Please review the changes and merge if everything looks good.
        branch: dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          maintenance



