name: Create Issue on Build Failure

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download workflow artifacts
      uses: actions/download-artifact@v4
      if: always()
      with:
        path: ./artifacts

    - name: Create issue on failure
      uses: actions/github-script@v7
      with:
        script: |
          const { data: workflow } = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id
          });

          const issueBody = `
          ## 🚨 Build Failed

          **Workflow:** ${workflow.name}
          **Run ID:** ${workflow.id}
          **Branch:** ${workflow.head_branch}
          **Commit:** ${workflow.head_sha}
          **Triggered by:** ${workflow.triggering_actor.login}

          **Run URL:** ${workflow.html_url}

          ### Details
          The CI/CD pipeline failed. Please check the workflow logs for more details.

          ### Next Steps
          1. Review the workflow logs
          2. Fix any issues found
          3. Push changes to trigger a new build
          `;

          // Check if issue already exists for this workflow run
          const existingIssues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['build-failure', 'automated'],
            state: 'open'
          });

          const existingIssue = existingIssues.data.find(issue =>
            issue.body && issue.body.includes(`Run ID: ${workflow.id}`)
          );

          if (!existingIssue) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Build Failed - ${workflow.head_branch}`,
              body: issueBody,
              labels: ['build-failure', 'automated', 'bug']
            });
          }


